#include <stdio.h>
#include "attendence_2.h"
int attendence_1(int rollno)
{
	int roll=rollno;
	float attendence;
	switch(roll)
	{
		case 1 : attendence=70.5;
				 return(attendence);
		case 2 : attendence=55.8;
				 return(attendence);
		case 3 : attendence=82.3;
				 return(attendence);
		case 4 : attendence=82.3;
				 return(attendence);
		case 5 : attendence=82.3;
				 return(attendence);
		case 6 : attendence=58.8;
				 return(attendence);
		case 7 : attendence=73.5;
				 return(attendence);
		case 8 : attendence=85.2;
				 return(attendence);
		case 9 : attendence=100;
				 return(attendence);
		case 10: attendence=61.7;
				 return(attendence);
		case 11: attendence=41.1;
				 return(attendence);
		case 12: attendence=26.4;
				 return(attendence);
		case 13: attendence=79.4;
				 return(attendence);
		case 14: attendence=70.5;
				 return(attendence);
		case 15: attendence=61.7;
				 return(attendence);
		case 16: attendence=55.8;
				 return(attendence);
		case 17: attendence=91.1;
				 return(attendence);
		case 18: attendence=67.6;
				 return(attendence);
		case 19: attendence=79.4;
				 return(attendence);
		case 20: attendence=85.2;
				 return(attendence);
		case 21: attendence=76.4;
				 return(attendence);
		case 22: attendence=55.8;
				 return(attendence);
		case 23: attendence=50;
				 return(attendence);
		case 24: attendence=73.5;
				 return(attendence);
		case 25: attendence=79.4;
				 return(attendence);
		case 26: attendence=79.4;
				 return(attendence);
		case 27: attendence=70.5;
				 return(attendence);
		case 28: attendence=88.2;
				 return(attendence);
		case 29: attendence=58.8;
				 return(attendence);
		case 30: attendence=52.9;
				 return(attendence);
		case 31: attendence=82.3;
				 return(attendence);
		case 32: attendence=97;
				 return(attendence);
		case 33: attendence=64.7;
				 return(attendence);
		case 34: attendence=97;
				 return(attendence);
		case 35: attendence=94.1;
				 return(attendence);
		case 36: attendence=52.9;
				 return(attendence);
		case 37: attendence=73.5;
				 return(attendence);
		case 38: attendence=67.6;
				 return(attendence);
		case 39: attendence=61.7;
				 return(attendence);
		case 40: attendence=41.1;
				 return(attendence);
		case 41: attendence=88.2;
				 return(attendence);
		case 42: attendence=79.4;
				 return(attendence);
		case 43: attendence=73.5;
				 return(attendence);
		case 44: attendence=82.3;
				 return(attendence);
		case 45: attendence=79.4;
				 return(attendence);
		case 46: attendence=61.7;
				 return(attendence);
		case 47: attendence=76.4;
				 return(attendence);
		case 48: attendence=70.5;
				 return(attendence);
		case 49: attendence=73.5;
				 return(attendence);
		case 50: attendence=76.4;
				 return(attendence);
		default :attendence_2(rollno);
	}
}